package com.wordpress.code2blog.code2blog_springboot_dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

@DynamoDBTable(tableName = "users")
public class UserModel implements Serializable {

	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@DynamoDBHashKey(attributeName = "UserId")
	@DynamoDBAutoGeneratedKey
	private String userId;

	@Getter
	@Setter
	@DynamoDBAttribute
	private String firstName;

	@Getter
	@Setter
	@DynamoDBAttribute
	private String lastName;

	@Getter
	@Setter
	@DynamoDBAttribute
	private String age;

}
