amazon:
  access:
    key: AKIAW26JXU4EWC4L5RWS
    secret-key: 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
  region: us-east-2
  end-point:
    url: dynamodb.us-east-2.amazonaws.com
server:
  port: 9001